### PR TITLE
Fix - Stylelint SCSS support

### LINKED ISSUE #276: Unknown rule `scss/at-rule-no-unknown`
### Describe the bug

The rule `scss/at-rule-no-unknown` does not exist on stylelint. Usages of this package outside of `toolkit` cause the above error.

```
Unknown rule scss/at-rule-no-unknown. Did you mean scss/at-rule-no-unknown at-rule-no-unknown?
```

### Steps to Reproduce

Need to install this outside of `toolkit` which does install `stylelint-config-standard-scss` and then try to run lint.

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Antonio-Laguna**
Fixes Issue/RFC: #276

This is a regression from #261

### Description of the Change

SCSS rule inserted is not supported out of the box though it is in the context of toolkit. This fixes that by creating a separate file that can be leveraged.

### Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/10up/10up-toolkit/blob/develop/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [X] All new and existing tests passed.
- [X] I have added a changeset to my PR. See [**CONTRIBUTING**](https://github.com/10up/10up-toolkit/blob/develop/CONTRIBUTING.md) document for instructions

### CODE REVIEW

File: packages/stylelint-config/scss.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+module.exports = {
+	extends: ['./index.js'],
+	rules: {
+		'scss/at-rule-no-unknown': [true, { ignoreAtRules: ['mixin', 'define-mixin'] }],
```
Comment (nicholasio) [inline packages/stylelint-config/scss.js:5]: Aren't you missing removing this rule from `index.js`?

**Review by nicholasio — CHANGES_REQUESTED** [review]

File: packages/stylelint-config/scss.js (hunk 1 above)
Comment (Antonio-Laguna) [reply packages/stylelint-config/scss.js:5]: @nicholasio what a dumb mistake on my end! You're right! I took it a step forward with the exports, let me know your thoughts!

**Review by nicholasio — APPROVED** [review]
