### PR TITLE
Checking chunk path for block decission

### LINKED ISSUE #264: Blocks: editor.css and related source map is only generated if the entry name contains the string 'block'
### Describe the bug

When running `10uptoolkit build` or `10uptoolkit watch`, if the key for an entry doesn't contain the string `block` then crucial block assets aren't generated. Instead of generating `dist/blocks/blockname/editor.css`, a file is created in `dist/css` with the entry key as the filename.

I expect that regardless of what the key is named, if the entry point path contains the block directory as set in `paths.config.js` then the appropriate assets are generated.

If the current behavior is intended, this should be documented clearly in the package readme.

### Steps to Reproduce

1. Create a basic block `example` in a project using 10up-toolkit that imports a CSS file in `block/index.js`
2. In `package.json`, create an entry for your new block, making sure not to include the string `block` in the entry key
3. Run `10uptoolkit build` or `10uptoolkit watch`
4. Observe that the contents of the previously imported CSS file are now in `dist/css/example.css` instead of `dist/blocks/example/editor.css`

### Screenshots, screen recording, code snippet

**Example entry**
`"image-carousel": "./includes/blocks/image-carousel/index.js",`

### Environment information

Using 10up-toolkit `v4.3.1`

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #277: Build error when no markup.php files
### Describe the bug

1. When running `10up-toolkit build` 
2. If I have no files that match the glob `/path/to/my/site/wp-content/themes/my-theme/includes/blocks/**/markup.php`
3. I get the following error: 

```
ERROR in unable to locate '/path/to/my/site/wp-content/themes/my-theme/includes/blocks/**/markup.php' glob

webpack 5.75.0 compiled with 1 error in 3018 ms
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @my-theme/theme@1.0.0
```

4. And pipelines, builds, etc. can't proceed

Temporary workaround: create a markup.php file in any includes/blocks subdirectory in the theme, even if it's unused.

### Steps to Reproduce

1. Create a site using 10up scaffold and using 10up-toolkit to build
2. Remove any markup.php files in the includes/blocks subdirectories.
3. Run `npm run build` in the theme.
4. See the rerror

### Screenshots, screen recording, code snippet

Possibly related to: 

https://github.com/10up/10up-toolkit/blob/e1124ecd6671db4507402cba8cdabb92f971de45/packages/toolkit/config/webpack/plugins.js#L130

### Environment information

_No response_

### WordPress information

Latest 10up scaffold using latest 10up-toolkit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Antonio-Laguna**
#264

  
Related Issue/RFC: #

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/10up-toolkit/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests passed.
- [x] I have added a changeset to my PR. See [**CONTRIBUTING**](https://github.com/10up/10up-toolkit/blob/develop/CONTRIBUTING.md) document for instructions

### CODE REVIEW

**Comment by Antonio-Laguna** [comment]
I was about to give up on this since WebPack's docs are terrible and console.log gave me little information so I had to investigate the prototype and source codes to find a way to extract the chunk's path. 

I'm tempted to remove the check by name and _just_ rely on directory belonging but I fear it might break.

I've assigned it for double checking (though there's not much code there changed) but also it'd be good if you could manually change this within a couple of project's node_module/10up-toolkit/config/webpack/plugins.js and copy this fix. Ideally, everything should behave normally but you no longer need a `-block-` prefix anywhere.

**Comment by roseg43** [comment]
@Antonio-Laguna Thanks for putting in a PR for this so quickly! I'll take a look early this week and confirm that this is working as expected

**Comment by roseg43** [comment]
@Antonio-Laguna I tested this manually on a project this morning and while I'm not seeing any errors when running `10up-toolkit build`, I am getting the following error when attempting to use the `watch` command:

```
Module.entryModule: Multiple entry modules are not supported by the deprecated API (Use the new ChunkGroup API)
Error: Module.entryModule: Multiple entry modules are not supported by the deprecated API (Use the new ChunkGroup API)
    at Chunk.get entryModule [as entryModule] (/Users/gabrielrose/Local Sites/<sitename>/app/public/wp-content/plugins/custom-block-library/node_modules/webpack/lib/Chunk.js:122:10)
    at filename (/Users/gabrielrose/Local Sites/<sitename>/app/public/wp-content/plugins/custom-block-library/node_modules/10up-toolkit/config/webpack/plugins.js:106:36)
```

**Comment by Antonio-Laguna** [comment]
@roseg43 that's odd. I have tried it on the local theme and it works perfectly. I'm surprised it would break like that since this does not add anything new but will match more cases rather than just being `-block` in the name. The rest is identical.

@fabiankaegy could you double-check this to see if the output is as expected?

**Comment by Antonio-Laguna** [comment]
Going to tackle #277 here as this touches the same area

File: packages/toolkit/config/webpack/plugins.js [hunk 1]
```diff
@@ -103,9 +103,19 @@ module.exports = ({
 					return removeDistFolder(style);
 				}
 
-				const isBlockAsset = useBlockAssets
-					? buildFiles[options.chunk.name].match(/\/blocks\//)
-					: options.chunk.name.match(/-block$/);
+				const fullPath = options.chunk.entryModule.identifier().split('!').pop();
```
Comment (nicholasio) [inline packages/toolkit/config/webpack/plugins.js]: I think this has the potential to cause issues... and the reason is that things can get really confusing.....

If `useBlocksAsset` is being used then `filenames` is overridden [here](https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/config/webpack/entry.js#L18) and that makes things work mostly fine. (now that I see where filenames variable is being changed I realize that is not the best place as it causes side-effects elsewhere - it took me a while to figure out who was mutating that variable)

But when `useBlocksAsset` is not set to true which is the default behavior then `filenames.blockCSS` is `blocks/[name]/editor.css`. Then here's what happens:

- The CSS is generated at `blocks/[name]/editor.css`
- Any CSS file imported from the JS of the block would also be generated at `blocks/[name]/editor.css` (currently this ends up being generated at `css/[name].css` - which is the value of `filenames.css`.
 
 I actually think this is the issue @roseg43 is running into https://github.com/10up/10up-toolkit/pull/267#issuecomment-1410799411 (@roseg43  are you using `useBlocksAssets`?)

I think the following code would be backwards compatible:

```js
// this returns what you want but would be undefined for CSS 
// that comes from non-css files (e.g CSS imported via JS)
const fullPath = options.chunk.entryModule.resource; 
if (!fullPath) {
 return filenames.css;
}
```

I did just a few tests but I'm thinking we should document the current behavior just to be extra sure of how it works and make sure the changes here do not break the current behavior.

Comment (nicholasio) [reply packages/toolkit/config/webpack/plugins.js]: The local theme we use for testing things has `useBlocksAssets` enabled so that's prob why @Antonio-Laguna wasn't running into this issue.

Comment (Antonio-Laguna) [reply packages/toolkit/config/webpack/plugins.js]: 🙇 thanks a lot @nicholasio I would have sworn that I had tested this in both scenarios but you're more than right! I've updated this

**Review by nicholasio — APPROVED** [review]

File: packages/toolkit/config/webpack/plugins.js (hunk 1 above)
Comment (roseg43) [reply packages/toolkit/config/webpack/plugins.js]: Ah yep, I definitely didn't have it enabled!
